version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres.ucjobduheixboosntjef:HariHaranLove@aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1"
      DIRECT_URL: "postgresql://postgres.ucjobduheixboosntjef:HariHaranLove@aws-1-ap-south-1.pooler.supabase.com:5432/postgres"
      PRISMA_CLI_BINARY_TARGETS: "linux-musl-openssl-3.0.x"